export const storeImages = [
  { src: require('../assets/store/birthdayboard.jpg') },
  { src: require('../assets/store/chart.jpg') },
  { src: require('../assets/store/cinchpack.png') },
  { src: require('../assets/store/cinchpack2.png') },
  { src: require('../assets/store/fullzipperhoodiesweatshirts.jpg') },
  { src: require('../assets/store/hoodiesweatshirts.png') },
  { src: require('../assets/store/lincolnpridefullzipperhoodie.jpg') },
  { src: require('../assets/store/lincolnpridefullzipperhoodie1.jpg') },
  { src: require('../assets/store/lincolnpridefullzipperhoodie2.jpg') },
  { src: require('../assets/store/lincthelionplushtoy.png') },
  { src: require('../assets/store/longsleevet-shirts.png') },
  { src: require('../assets/store/shortsleevet-shirts.png') },
  { src: require('../assets/store/sponsorship.png') },
  { src: require('../assets/store/staffonlyfleecejacket.jpg') },
  { src: require('../assets/store/staffonlypolot-shirt.jpg') },
  { src: require('../assets/store/staffptomembership.jpg') },
  { src: require('../assets/store/standardptomembership.png') },
  { src: require('../assets/store/sweatpants.jpg') },
  { src: require('../assets/store/sweatpants2.jpg') },
  { src: require('../assets/store/tie-dyeshortsleevet-shirts.jpg') },
  { src: require('../assets/store/tie-dye2.jpg') },
];
